CampusCourse/Controllers/CoursesController.cs
using CampusCourse.Data;
using CampusCourse.Models;
using CampusCourse.Models.CourseViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CampusCourse.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<User> userManager;
        public CoursesController(ApplicationDbContext context, UserManager<User> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Teacher")]
        [HttpGet]
        public async Task<IActionResult> Create(Guid? prototypeId)
        {
            var prototype = await this.context.Prototypes
               .SingleOrDefaultAsync(m => m.Id == prototypeId);

            ViewBag.PrototypeId = prototype.Id;

            var model = new CreateCourseViewModel()
            {
                Credits = prototype.Credits,
                Language = prototype.Language,
                Requirements = prototype.Requirements,
                Annotation = prototype.Annotation,
                Material = prototype.Material,
                Literature = prototype.Literature
            };

            return View(model);
        }

        [Authorize(Roles = "Admin, Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid? prototypeId, CreateCourseViewModel model)
        {
            var prototype = await this.context.Prototypes
               .SingleOrDefaultAsync(m => m.Id == prototypeId);

            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            ViewBag.PrototypeId = prototype.Id;

            if (this.ModelState.IsValid)
            {
                var course = new Course
                {
                    Creator = user,
                    Prototype = prototype,
                    Name = model.Name,
                    Credits = model.Credits,
                    Year = model.Year,
                    Semester = model.Semester,
                    TotalStudents = model.TotalStudents,
                    MinStudents = model.MinStudents,
                    Language = model.Language,
                    Requirements = model.Requirements,
                    Annotation = model.Annotation,
                    Material = model.Material,
                    Literature = model.Literature
                };
                this.context.Courses.Add(course);
                await this.context.SaveChangesAsync();
                return this.RedirectToAction("Details", "Prototypes", new { id = prototypeId });
            }

            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var course = await context.Courses
                .Include(x => x.Schedules)
                .Include(x => x.Notifications)
                .Include(x => x.StudentCourses)
                .FirstOrDefaultAsync(m => m.Id == id);

            return View(new CourseDetailViewModel { course=course});
        }

        [Authorize(Roles = "Admin, Teacher")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var course = await this.context.Courses
                .SingleOrDefaultAsync(x => x.Id == id);
            var prototype = course.Prototype;

            var model = new EditCourseViewModel()
            {
                Name = course.Name,
                Credits = course.Credits,
                Language = course.Language,
                Requirements = course.Requirements,
                Annotation = course.Annotation,
                Material = course.Material,
                Literature = course.Literature,
                Year = course.Year,
                Semester = course.Semester,
                TotalStudents = course.TotalStudents,
                MinStudents = course.MinStudents
            };

            return this.View(model);
        }

        [Authorize(Roles = "Admin, Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, EditCourseViewModel model)
        {
            var course = await this.context.Courses
                .SingleOrDefaultAsync(x => x.Id == id);
            var prototype = course.Prototype;
            if(this.ModelState.IsValid)
            {
                course.Name = model.Name;
                course.Credits = model.Credits;
                course.Language = model.Language;
                course.Requirements = model.Requirements;
                course.Annotation = model.Annotation;
                course.Material = model.Material;
                course.Literature = model.Language;
                course.Year = model.Year;
                course.Semester = model.Semester;
                course.TotalStudents = model.TotalStudents;
                course.MinStudents = model.MinStudents;
                await this.context.SaveChangesAsync();
                return RedirectToAction("Index", "Groups");
            };


            return this.View(model);
        }

        [Authorize(Roles = "Admin, Teacher")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var course = await this.context.Courses.SingleOrDefaultAsync(m => m.Id == id);
            var prototypeId = course.PrototypeId;

            this.context.Courses.Remove(course);
            await context.SaveChangesAsync();
            return this.RedirectToAction("Details", "Prototypes", new { id = prototypeId });
        }
    }
}

CampusCourse/Controllers/NotificationsController.cs
using CampusCourse.Data;
using CampusCourse.Models;
using CampusCourse.Models.CourseViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CampusCourse.Controllers
{
    public class NotificationsController : Controller
    {
        private readonly ApplicationDbContext context;
        public NotificationsController(ApplicationDbContext context)
        {
            this.context = context;
        }
        [Authorize(Roles = "Admin, Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid courseId, CourseDetailViewModel model)
        {
            var course = this.context.Courses.FirstOrDefault(x => x.Id == courseId);
            if(this.ModelState.IsValid)
            {
                var now = DateTime.Now;
                var notification = new Notification
                {
                    Text = model.createNotificationViewModel.text,
                    Created = now,
                    CourseId = courseId
                };
                this.context.Notifications.Add(notification);
                await this.context.SaveChangesAsync();
                return this.RedirectToAction("Details", "Courses", new { id = courseId });
            }
            return View();
        }
    }
}

CampusCourse/Controllers/SchedulesController.cs
using CampusCourse.Data;
using CampusCourse.Models;
using CampusCourse.Models.CourseViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CampusCourse.Controllers
{
    public class SchedulesController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<User> userManager;
        public SchedulesController(ApplicationDbContext context, UserManager<User> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        [Authorize(Roles = "Admin, Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid courseId, CourseDetailViewModel model)
        {
            var course = this.context.Courses.FirstOrDefault(x => x.Id == courseId);
            if (this.ModelState.IsValid)
            {
                var schedule = new Schedule
                {
                    Day = model.createScheduleViewModel.Day,
                    Building = model.createScheduleViewModel.Building,
                    Class = model.createScheduleViewModel.Class,
                    StartTime = model.createScheduleViewModel.StartTime,
                    EndTime = model.createScheduleViewModel.EndTime,
                    CourseId = courseId
                };
                this.context.Schedules.Add(schedule);
                await this.context.SaveChangesAsync();
                return this.RedirectToAction("Details", "Courses", new { id = courseId });
            }

            return this.View();
        }
    }
}

CampusCourse/Controllers/StudentCourseController.cs
using CampusCourse.Data;
using CampusCourse.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CampusCourse.Controllers
{
    public class StudentCourseController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<User> userManager;
        public StudentCourseController(ApplicationDbContext context, UserManager<User> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> Create(Guid courseId)
        {
            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            if(this.ModelState.IsValid)
            {
                var studentcourse = new StudentCourse
                {
                    Student = user,
                    CourseId = courseId
                };
                this.context.StudentCourses.Add(studentcourse);
                await this.context.SaveChangesAsync();
                return this.RedirectToAction("Details", "Courses", new { id = courseId });
            }
            return View();
        }
    }
}

CampusCourse/Views/Courses/Create.cshtml
@model CampusCourse.Models.CourseViewModel.CreateCourseViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no,maximum-scale=1.0,minimum-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/course.css" />
</head>

<body>
    <div class="whole">
        <header class="hd">
            <h1>Course creation</h1>
        </header>
        <form method="post" asp-controller="Courses" asp-action="Create" asp-route-prototypeId="@ViewBag.PrototypeId">
            <div class="bd w">
                <div class="fir">
                    <p>Course Name</p>
                    <input type="text" asp-for="Name">
                </div>

                <div class="sec">
                    <div class="left">
                        <p>Credits</p>
                        <input type="number" placeholder="0" asp-for="Credits">
                    </div>
                    <div class="rig">
                        <p>Languages</p>
                        <input asp-for="Language" value="Russian" type="radio"><span>Russian</span>
                        <input asp-for="Language" value="English" type="radio"><span>English</span>
                        <input asp-for="Language" value="German" type="radio"><span>German</span>
                        <input asp-for="Language" value="Franch" type="radio"><span>Franch</span>
                    </div>
                </div>

                <div class="line">
                    <div class="year">
                        <p>Year</p>
                        <select type="text" asp-for="Year">
                            <option>2020-2021</option>
                            <option>2021-2022</option>
                            <option>2022-2023</option>
                            <option>2023-2024</option>
                        </select>
                    </div>
                    <div class="semester">
                        <p>Semester</p>
                        <select type="text" asp-for="Semester">
                            <option>Spring Semester</option>
                            <option>Autumn Semester</option>
                        </select>
                    </div>
                    <div class="total">
                        <p>Total Student Count</p>
                        <input type="text" asp-for="TotalStudents">
                    </div>
                    <div class="min">
                        <p>Students Minimum Count</p>
                        <input type="text" asp-for="MinStudents">
                    </div>
                </div>

                <div class="thi">
                    <p>Requirements</p>
                    <textarea asp-for="Requirements" name="Requirements" id="" cols="30" rows="10"></textarea>
                </div>

                <div class="fourth">
                    <p>Annotation</p>
                    <textarea asp-for="Annotation" name="Annotation" id="" cols="30" rows="10"></textarea>
                </div>

                <div class="fifth">
                    <p>Materials</p>
                    <textarea asp-for="Material" name="Material" id="" cols="30" rows="10"></textarea>
                </div>

                <div class="sixth">
                    <p>Literature</p>
                    <textarea asp-for="Literature" name="Literature" id="" cols="30" rows="10"></textarea>
                </div>

                <div class="seventh">
                    <button type="submit">Submit</button>
                </div>
            </div>
        </form>
    </div>
</body>

</html>

<script src="~/js/ckeditor/ckeditor.js"></script>
<script>CKEDITOR.replace('Requirements');</script>
<script>CKEDITOR.replace('Annotation');</script>
<script>CKEDITOR.replace('Material');</script>
<script>CKEDITOR.replace('Literature');</script>

CampusCourse/Views/Courses/Details.cshtml
@model CampusCourse.Models.CourseViewModel.CourseDetailViewModel
@inject CampusCourse.Services.UserService UserService
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/courseDetail.css" />
</head>

<body>
    <h1>Campus Course - @Model.course.Name</h1>
    <div class="main">
        <ul class="course">
            <li class="first">
                <h2>Main course data</h2>
                <form method="post" asp-action="Create" asp-controller="StudentCourse" asp-route-courseId="@Model.course.Id">
                    <button class="edit">Join Course</button>
                </form>
                
            </li>
            <li class="second">
                <div class="left">
                    <span class="element">STATUS</span>
                    <span class="data">Midterm passed</span>
                </div>
                <a class="change">Change Status</a>
            </li>
            <li class="third">
                <div class="left">
                    <span class="element">Year</span>
                    <span class="data">@Model.course.Year</span>
                </div>
                <div class="right">
                    <span class="element">Semester</span>
                    <span class="data">@Model.course.Semester</span>
                </div>
            </li>
            <li class="fourth">
                <div class="left">
                    <span class="element">Creadits / Hours</span>
                    <span class="data">@Model.course.Credits / 72,00</span>
                </div>
                <div class="right">
                    <span class="element">Total Places Count</span>
                    <span class="data">100</span>
                </div>
            </li>
            <li class="fifth">
                <div class="left">
                    <span class="element">Student Assigned</span>
                    <span class="data">24</span>
                </div>
                <div class="right">
                    <span class="element">Requests for assigning in queue</span>
                    <span class="data">0</span>
                </div>
            </li>
            <li class="sixth">
                <div class="left">
                    <span class="element">Language</span>
                    <span class="data">@Model.course.Language</span>
                </div>
            </li>
        </ul>
    </div>

    <div class="tab">
        <div class="tab_list" id='tabList'>
            <ul class="tabul">
                <li class="color">Requirements</li>
                <li>Annotation</li>
                <li>Materials</li>
                <li>Literature</li>
            </ul>
        </div>
        <div class="tab_con" id='tabCon'>
            <div class="tab-item" style="display: block;">@Html.Raw(@Model.course.Requirements)</div>
            <div class="tab-item" style="display: none;">@Html.Raw(@Model.course.Annotation)</div>
            <div class="tab-item" style="display: none;">@Html.Raw(@Model.course.Material)</div>
            <div class="tab-item" style="display: none;">@Html.Raw(@Model.course.Literature)</div>
        </div>
    </div>

    <div class="tab2">
        <div class="tab_list" id='tabList2'>
            <ul class="tabul">
                <li class="color">Teachers</li>
                <li>Students</li>
                <li>Schedule</li>
                <li>Notifications</li>
            </ul>
        </div>
        <div class="tab_con2" id='tabCon2'>
            <div class="tab-item" style="display: block;">
                <img src="~/uploads/@await UserService.GetTeacher(Model.course.CreatorId)" style="height:100px; width:100px" class="circle" />
                <span>@Model.course.Creator.FullName</span>
            </div>
            <div class="tab-item" style="display: none;">
                @foreach (var item in Model.course.StudentCourses)
                {
                    <img src="~/uploads/@await UserService.GetTeacher(item.StudentId)" style="height:100px; width:100px" class="circle" />
                    <span>@item.Student.FullName</span>
                }
            </div>
            <div class="tab-item" style="display: none;">
                <form method="post" asp-action="Create" asp-controller="Schedules" asp-route-courseId="@Model.course.Id">
                    <div class="row" style="margin-left:0px;margin-right:0px;">
                        <div class="form-group col-md-2">
                            <label style="text-indent:0em;">Day of week</label>
                            <select asp-for="createScheduleViewModel.Day" class="form-control">
                                <option>Monday</option>
                                <option>Tuesday</option>
                                <option>Wednesday</option>
                                <option>Thursday</option>
                                <option>Friday</option>
                                <option>Saturday</option>
                                <option>Sunday</option>
                            </select>
                        </div>
                        <div class="form-group col-md-2">
                            <label>Building</label>
                            <input asp-for="createScheduleViewModel.Building" class="form-control" />
                        </div>
                        <div class="form-group col-md-2">
                            <label>Class</label>
                            <input asp-for="createScheduleViewModel.Class" class="form-control" />
                        </div>
                        <div class="form-group col-md-2">
                            <label>Start time</label>
                            <input asp-for="createScheduleViewModel.StartTime" type="datetime-local" class="form-control" />
                        </div>
                        <div class="form-group col-md-2">
                            <label>End time</label>
                            <input asp-for="createScheduleViewModel.EndTime" type="datetime-local" class="form-control" />
                        </div>
                        <div class="form-group col-md-2">
                            <button class="btn btn-primary" style="margin-top:30px">Create</button>
                        </div>
                    </div>
                    <div class="row" style="margin-left:0px;margin-right:0px;">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Day of week</th>
                                    <th scope="col">Building</th>
                                    <th scope="col">Class</th>
                                    <th scope="col">Star time</th>
                                    <th scope="col">End time</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.course.Schedules)
                                {
                                    <tr>
                                        <td>@item.Day</td>
                                        <td>@item.Building</td>
                                        <td>@item.Class</td>
                                        <td>@item.StartTime</td>
                                        <td>@item.EndTime</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
            <div class="tab-item" style="display: none;">
                <form method="post" asp-action="Create" asp-controller="Notifications" asp-route-courseId="@Model.course.Id">
                    <div class="row" style="margin-left:0px;margin-right:0px;margin-top:15px;">
                        <div class="form-group col-md-6">
                            <input asp-for="createNotificationViewModel.text" placeholder="notification text" class="form-control" />
                        </div>
                        <div class="form-group col-md-2">
                            <button class="btn btn-primary">Add</button>
                        </div>
                    </div>
                </form>
                @foreach (var item in Model.course.Notifications)
                {
                    <div class="row" style="margin-left:15px;margin-right:0px;">
                        <svg style="margin-top:5px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
                            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z" />
                        </svg>@item.Text
                    </div>
                    <div style="color:#C1BBBB;margin-left:15px">@item.Created.ToShortTimeString()</div>
                    <hr style="margin:0px; margin-bottom: 4px"/>
                }
            </div>
    </div>


    <script>
        var tabList = document.getElementById('tabList');
        var tabList2 = document.getElementById('tabList2');
        var lis = tabList.querySelectorAll('li');
        var lis2 = tabList2.querySelectorAll('li');
        var tabCon = document.getElementById('tabCon');
        var item = tabCon.getElementsByClassName('tab-item');
        var tabCon2 = document.getElementById('tabCon2');
        var item2 = tabCon2.getElementsByClassName('tab-item');
        for (var i = 0; i < lis.length; i++) {
            lis[i].setAttribute('index', i);
            lis[i].onclick = function () {
                for (var i = 0; i < lis.length; i++) {
                    lis[i].className = '';
                    item[i].style.display = 'none';
                }
                this.className = 'color';
                var index = this.getAttribute('index');
                item[index].style.display = 'block';
            };
        }

        for (var i = 0; i < lis2.length; i++) {
            lis2[i].setAttribute('index', i);
            lis2[i].onclick = function () {
                for (var i = 0; i < lis2.length; i++) {
                    lis2[i].className = '';
                    item2[i].style.display = 'none';
                }
                this.className = 'color';
                var index = this.getAttribute('index');
                item2[index].style.display = 'block';
            };
        }
    </script>
</body>
</html>

CampusCourse/Views/Courses/Edit.cshtml
@model CampusCourse.Models.CourseViewModel.EditCourseViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no,maximum-scale=1.0,minimum-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/course.css" />
</head>

<body>
    <div class="whole">
        <header class="hd">
            <h1>Edit Course</h1>
        </header>
        <form method="post" asp-controller="Courses" asp-action="Edit">
            <div class="bd w">
                <div class="fir">
                    <p>Course Name</p>
                    <input type="text" asp-for="Name">
                </div>

                <div class="sec">
                    <div class="left">
                        <p>Credits</p>
                        <input type="number" placeholder="0" asp-for="Credits">
                    </div>
                    <div class="rig">
                        <p>Languages</p>
                        <input asp-for="Language" value="Russian" type="radio"><span>Russian</span>
                        <input asp-for="Language" value="English" type="radio"><span>English</span>
                        <input asp-for="Language" value="German" type="radio"><span>German</span>
                        <input asp-for="Language" value="Franch" type="radio"><span>Franch</span>
                    </div>
                </div>

                <div class="line">
                    <div class="year">
                        <p>Year</p>
                        <select type="text" asp-for="Year">
                            <option>2020-2021</option>
                            <option>2021-2022</option>
                            <option>2022-2023</option>
                            <option>2023-2024</option>
                        </select>
                    </div>
                    <div class="semester">
                        <p>Semester</p>
                        <select type="text" asp-for="Semester">
                            <option>Spring Semester</option>
                            <option>Autumn Semester</option>
                        </select>
                    </div>
                    <div class="total">
                        <p>Total Student Count</p>
                        <input type="text" asp-for="TotalStudents">
                    </div>
                    <div class="min">
                        <p>Students Minimum Count</p>
                        <input type="text" asp-for="MinStudents">
                    </div>
                </div>

                <div class="thi">
                    <p>Requirements</p>
                    <textarea asp-for="Requirements" name="Requirements" id="" cols="30" rows="10"></textarea>
                </div>

                <div class="fourth">
                    <p>Annotation</p>
                    <textarea asp-for="Annotation" name="Annotation" id="" cols="30" rows="10"></textarea>
                </div>

                <div class="fifth">
                    <p>Materials</p>
                    <textarea asp-for="Material" name="Material" id="" cols="30" rows="10"></textarea>
                </div>

                <div class="sixth">
                    <p>Literature</p>
                    <textarea asp-for="Literature" name="Literature" id="" cols="30" rows="10"></textarea>
                </div>

                <div class="seventh">
                    <button type="submit">Submit</button>
                </div>
            </div>
        </form>
    </div>
</body>

</html>

<script src="~/js/ckeditor/ckeditor.js"></script>
<script>CKEDITOR.replace('Requirements');</script>
<script>CKEDITOR.replace('Annotation');</script>
<script>CKEDITOR.replace('Material');</script>
<script>CKEDITOR.replace('Literature');</script>